name: scimine_env
channels:
  - defaults
dependencies:
  - python=3.9
  - pandas
  - numpy==1.26.4
  - scikit-learn 
  - pytorch
  - seaborn
  - nltk
  - requests
  - beautifulsoup4
  - gensim
  - pip:
      - transformers==4.48.0
      - synergy_dataset
      - aiohttp
      - python-louvain
